version: "3.2"
services:
  php:
    image: chandra9853/inkxe_x_test_1:php56
    networks:
      - backend
  apache:
    container_name: php72
    image: chandra9853/inkxe_x_test_1:php72
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
     - ../../xeprojects:/var/xeprojects
     - ./sites-available/magento1924.inkxe.com.conf:/etc/apache2/sites-available/magento1924.inkxe.com.conf
     - ./sites-available/prestashop.inkxe.com.conf:/etc/apache2/sites-available/prestashop.inkxe.com.conf
     - ./sites-available/wc3.inkxe.com.conf:/etc/apache2/sites-available/wc3.inkxe.com.conf
    #command: bash -c "sleep 20 && cp -a /var/www/html/xeprojects/. /var/xeprojects"
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_schema/basic_database.sql:/docker-entrypoint-initdb.d/basic_database.sql
  phpmyadmin:
     container_name: inkxe10_phpmyadmin
     depends_on:
      - mysql
     image: phpmyadmin/phpmyadmin
     restart: always
     networks:
      - frontend
      - backend
     ports:
      - 8080:80
     environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'root'
networks:
  frontend:
  backend:
volumes:
    db_data: {}